enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "MorpheApp/morphe-cli"
patches-source = "MorpheApp/morphe-patches"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[Music]
#enabled = false
app-name = "Music"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
excluded-patches = """\
  'Custom branding' \
  """
enable-update-checks = true

[YouTube]
#enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
excluded-patches = """\
  'Custom branding' \
  """
enable-update-checks = true

[Reddit]
#enabled = false
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
enable-update-checks = true

[Instagram]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
direct-dlurl = "https://temp.sh/jvpoT/com.instagram.android-439.0.0.37.89-arm64-v8a.apk"
enable-update-checks = true
arch = "arm64-v8a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"

[News]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news"

[Photomath]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath"
dpi = "120-640dpi"
